#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/public"])
env.Append(CPPDEFINES=["ORC_RENDERER_EXPORTS"])
    
env['OBJSUFFIX'] = '.o'

src_dir = "src/private"
obj_dir = "obj"
VariantDir(obj_dir, src_dir, duplicate=0)
sources = Glob(os.path.join(obj_dir, "*.cpp"))

if env["target"] == "template_debug":
    print("Building with test sources (DEBUG build)")
    tests_dir = "src/tests"
    VariantDir(os.path.join(obj_dir, "tests"), tests_dir, duplicate=0)
    sources += Glob(os.path.join(obj_dir, "tests", "*.cpp"))
    env.Append(CPPPATH=[tests_dir])

    print("Building with dbg sources (DEBUG build)")
    dbg_dir = "src/dbg"
    VariantDir(os.path.join(obj_dir, "dbg"), dbg_dir, duplicate=0)
    sources += Glob(os.path.join(obj_dir, "dbg", "*.cpp"))
    env.Append(CPPPATH=[dbg_dir])

library = env.SharedLibrary(
    "bin/liborc{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

Default(library)
